# coding: utf8

# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1200x900")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 900,
    width = 1200,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    600.0,
    450.0,
    image=image_image_1
)

canvas.create_rectangle(
    0.0,
    0.0,
    1200.0,
    900.0,
    fill="#F4F4F4",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    291.666748046875,
    900.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    28.0,
    129.0,
    69.0,
    179.0,
    fill="#0A529E",
    outline="")

canvas.create_text(
    321.0,
    670.0,
    anchor="nw",
    text="  Enigma-Tester est une application qui sert � mesurer le temps d�ex�cution de plusieurs algorithmes de chiffrement et les illustrent dans un dashboard ",
    fill="#110F0F",
    font=("Inter ExtraBold", 24 * -1)
)

canvas.create_text(
    139.0,
    851.0,
    anchor="nw",
    text="copyright\nALL rights reserved",
    fill="#FFFFFF",
    font=("Inter ExtraBold", 10 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=81.0,
    y=227.0,
    width=199.1666259765625,
    height=65.0390625
)

canvas.create_rectangle(
    0.0,
    0.0,
    280.485107421875,
    899.999267578125,
    fill="#0A529E",
    outline="")

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=600.0,
    y=793.0,
    width=242.5,
    height=75.5859375
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    742.0,
    333.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    114.0,
    866.0,
    image=image_image_3
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    179.58331298828125,
    159.08203125,
    image=entry_image_1
)
canvas.create_text(
    109.0,
    161.0,
    anchor="nw",
    fill="#FFFFFF",
    font=("Inter ExtraBold", 26 * -1)
)
window.resizable(False, False)
window.mainloop()
